//import fs from 'fs';
import matter from 'gray-matter';
import Link from 'next/link';
import PostCard from '../components/PostCard';
import useSWR from 'swr';
import axios from 'axios';
import { fetcher } from '../utils';
import { loadPosts } from '../utils/index';
//import { storage } from '../firebase/firebase';
// import * as admin from "firebase-admin";

export const getStaticProps = async () => {
//   if (!admin.apps.length) {
//     //firebase.initializeApp(firebaseConfig);
//     admin.initializeApp({ storageBucket: "simple-git-test.appspot.com" });
//     console.log('initialize firebase!!')
// }
  // const storage = admin.storage();
  // const bucket = storage.bucket();
  //console.log(bucket);
  // const file = storage.bucket().file("blogData.txt");
  // try {
  //   const downloadFile = await file.download();
  //   //(new TextDecoder).decode(Uint8Array.of(...downloadFile))
  //   console.log(downloadFile);
  //   console.log(downloadFile.toString());
  // } catch (err) {
  //   console.log(err);
  // }
  
  //const files = fs.readdirSync('posts');
  const posts = await loadPosts();
  //console.log(posts);
  // const posts = files.map((fileName) => {
  //   const slug = fileName.replace(/\.md$/, '');
  //   const fileContent = fs.readFileSync(`posts/${fileName}`, 'utf-8');
  //   const { data } = matter(fileContent);
  //   return {
  //     frontMatter: data,
  //     slug,
  //   };
  // });
  
  const sortedPosts = posts.sort((postA, postB) =>
    new Date(postA.metadata.date) > new Date(postB.metadata.date) ? -1 : 1
  );
  // const url = 'https://storage.googleapis.com/simple-git-test.appspot.com/blogData.txt';
  // const res = await fetch(url);
  // const postsJson = JSON.parse(JSON.stringify(res));
  return {
    props: {
      posts: sortedPosts,
    },
  };
};

// export const loadPosts = async () => {
  
//   // const fileRef = storage.ref('blogData.txt');
//   // const url = await fileRef.getDownloadURL();
//   // console.log(url);
//   //const { data, error } = useSWR('https://storage.googleapis.com/simple-git-test.appspot.com/blogData.txt', axios);
//   // const res = await fetch('https://storage.googleapis.com/simple-git-test.appspot.com/blogData.txt');
//   // const data = await res.json();
//   const res = await axios('https://storage.googleapis.com/simple-git-test.appspot.com/blogData.txt')
//   // const data = JSON.parse(res);
//   // console.log(res.data);
//   // console.log(JSON.stringify(res.data));
//   //const data = JSON.parse(JSON.stringify(res.data);
//   //console.log(res.data);
//   return res.data;
// }

export default function Home({ posts }) {
  return (
    <div className="my-8">
      <div className="grid grid-cols-3 gap-4">
        {posts.map((post) => (
          <PostCard key={post.metadata.slug} post={post} />
        ))}
      </div>
    </div>
  );
}

// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// export default function Home() {
//   return (
//     <div >
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main >
//       </main>
//     </div>
//   )
// }
